apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: helmnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helm-operator
  template:
    metadata:
      labels:
        name: helm-operator
    spec:
      serviceAccountName: helm-operator
      containers:
        - name: helm-operator
          # Replace this with the built image name
          image: arbhoj/helm-operator:v1.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "helm-operator"
