apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sdk-operator
  template:
    metadata:
      labels:
        name: sdk-operator
    spec:
      serviceAccountName: sdk-operator
      containers:
        - name: sdk-operator
          # Replace this with the built image name
          image: arbhoj/sdk-operator:v1.0.5
          command:
          - sdk-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sdk-operator"
