---
- hosts: all
  gather_facts: no
  tasks: 
  - name: Take a backup
    uri:
      url: 'http://run-nginxansible-service.{{ meta.namespace }}:80'
      body_format: raw
      dest: '/tmp/{{ meta.name }}_backup.txt'
