apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmtests.helm.example.com
spec:
  group: helm.example.com
  names:
    kind: Helmtest
    listKind: HelmtestList
    plural: helmtests
    singular: helmtest
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
