apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: createbackups.ansible.operator.com
spec:
  group: ansible.operator.com
  names:
    kind: CreateBackup 
    listKind: CreateBackupList
    plural: createbackups
    singular: createbackup
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
