replicas:
  description: "This is the number of replicas to be deployed"
  default: "1"
  
defaultBody:
  description: "This is the body of the default nginx page"
  default: "Hey I am default for version 3"
  trigger: "update"  

nodePort:
  description: "This is the port on which the service will be exposed on the nodes"
  default: "30080"
  trigger: "update"

containerPort:
  description: This is the container port
  default: 80
  trigger: do-nothing 
 
