apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  replicas: {{ .Params.replicas }}
  selector:
    matchLabels:
      run: my-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: {{ containerPort }}
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: myconfigmap
          subPath: index.html
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Name }}-my-conf
        name: myconfigmap

