apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Name }}-my-nginx
  name: {{ .Name }}-my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Params.nodePort }}
  selector:
    run: {{ .Name }}-my-nginx
  type: NodePort
