apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sdk-operator.com/v1alpha1",
          "kind": "NginxSDK",
          "metadata": {
            "name": "nginxsdk"
          },
          "spec": {
            "containerport": 80,
            "defaultbody": "This is the body",
            "nodeport": 31111,
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: sdk-operator-v2.v1.0.4
  namespace: newsdk
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Test description
      displayName: SDK Operator
      kind: NginxSDK
      name: nginxsdks.sdk-operator.com
      version: v1alpha1
  description: Placeholder description
  displayName: Sdk Operator V2
  install:
    spec:
      deployments:
      - name: sdk-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: sdk-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: sdk-operator
            spec:
              containers:
              - command:
                - sdk-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: sdk-operator
                image: arbhoj/sdk-operator:v1.0.4
                imagePullPolicy: Always
                name: sdk-operator
                resources: {}
              serviceAccountName: sdk-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sdk-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - sdk-operator.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: sdk-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: sdk-operator-v2.v1.0.3
  version: 1.0.4
