apiVersion: v1
kind: Service
metadata:
  labels:
    run: '{{ meta.name }}'
  name: '{{ meta.name }}-service'
  namespace: '{{ meta.namespace }}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ node_port }}
  selector:
    run: '{{ meta.name }}'
  type: NodePort
